#!/usr/bin/with-contenv bash

	exec \
	s6-setuidgid abc /utorrent/utserver \
	-settingspath /config -configfile /config/utserver.conf -logfile /config/log/utserver.log -pidfile /config/utserver.pid

until [ -e "/config/utserver.pid" ];
do
sleep 1s
done

utorrent_pid=$(< /config/utserver.pid cut -d '+' -f 2)

tail -n 1 -f /config/log/utserver.log "$utorrent_pid"